### ISSUE TITLE
"Pattern" image preview not showing in Gutenberg

### ISSUE THREAD

**Issue by gaiusjaugustus** [nk-o/awb#30]
Hello,
I'm in love with this plugin. Just want to report a (hopefully small) bug.

When I set an Image background to "Pattern", no image preview shows up.  The image preview shows fine for "Cover" and "Contain". In the below example, the white heading in the middle should have the pattern background seen on the right.

[
![image](https://user-images.githubusercontent.com/10555763/52510610-d987a380-2bb9-11e9-91b5-db0ebd7f3767.png)
]()

For clarity, there is NO issue with how it actually looks in the page/post. It is only the preview that does not show up.

Thanks again for the useful plugin.
Gaius

**Comment by nk-o** [comment]
Hi Gaius.

Fixed in https://github.com/nk-o/awb/commit/bff7a3d3c073cf8caace589fa4da69c755f8d0a8

Thank you.
