### ISSUE TITLE
Feature Request: Support adding borders

### ISSUE THREAD

**Issue by adamshand** [nk-o/awb#37]
Hey,

Love this plugin, thanks for your work and making it free.

What I'd find very helpful is it it allowed me to also add a border to a block.  I can't currently find anyway to do this other then custom CSS.

Best wishes from New Zealand,
Adam.

**Comment by nk-o** [comment]
Hi Adam.

Unfortunately, we don't have plans to add this to the AWB plugin. Borders and shadows will be added in our Ghost Kit plugin on the Gutenberg Group block in the next update https://wordpress.org/plugins/ghostkit/

**Comment by adamshand** [comment]
Thanks for the reply.  Looking forward to it being added to Ghostkit.
