### ISSUE TITLE
Parallax background image jerks / scrolls unsmoothmly on MS Edge like

### ISSUE THREAD

**Issue by Chris8080** [nk-o/awb#38]
Parallax background image jerks / scrolls unsmoothmly on MS Edge like 
https://github.com/nk-o/jarallax/issues/4
https://github.com/nk-o/jarallax/issues/25

It would be a good idea, if it's possible to deactivate the effect completely on Edge / IE or maybe there is another solution?

I've tried to add:
`var isIE = /MSIE 9/i.test(navigator.userAgent) || /rv:11.0/i.test(navigator.userAgent) || /MSIE 10/i.test(navigator.userAgent) || /Edge\/\d+/.test(navigator.userAgent);
jarallax(document.querySelectorAll('.jarallax'), {enableTransform: !isIE});
`
at the end of **jarallax.min.js** but that didn't improve anything.

**Comment by nk-o** [comment]
Hi.

You can disable parallax in settings - https://wpbackgrounds.com/documentation/settings/
