### ISSUE TITLE
Markup conflict with Unsplash

### ISSUE THREAD

**Issue by Youdaman** [nk-o/awb#39]
Not sure if this is caused by your plugin or Unsplash https://wordpress.org/plugins/unsplash/

After creating a AWB block and setting its background to use an image that's been uploaded/created via the Unsplash plugin, after saving the page and then re-opening the edit screen for that page, the block is broken. It can be fixed by choosing the Attempt Block Recovery menu item.

It looks like the AWB div is being mixed with markup for a figure element: `<dfiv class="nk-awb-inngurer">` instead of `<div class="nk-awb-inner">`

I'm guessing Unsplash is trying to wrap the image in a figure? Anyway just a heads up if people have any broken blocks after using your plugin, it could be an issue similar to this where another plugin tries to change the markup and mixes it.

**Comment by nk-o** [comment]
Hey.

Yes, I think their strange code behavior kills our block. I don't think their plugin is good, I prefer this alternative https://wordpress.org/plugins/instant-images/, which downloads images to your server and uses it in a normal native WordPress way.
